# Generated by Django 2.2.1 on 2019-05-22 09:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NsLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.EmailField(max_length=70)),
                ('date', models.DateField()),
                ('last_signin', models.DateTimeField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('last_logoff', models.DateTimeField(blank=True, null=True)),
                ('ip', models.CharField(max_length=70)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('user', 'date', 'timestamp', 'active'),
            },
        ),
        migrations.CreateModel(
            name='O365User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=70)),
            ],
            options={
                'ordering': ('email',),
            },
        ),
    ]
